<?php defined('SYSPATH') or die('No direct script access.');

return array(

	'uncountable' => array(
		'access',
		'advice',
		'aircraft',
		'art',
		'baggage',
		'bison',
		'dances',
		'deer',
		'equipment',
		'fish',
		'fuel',
		'furniture',
		'heat',
		'honey',
		'homework',
		'impatience',
		'information',
		'knowledge',
		'luggage',
		'media',
		'money',
		'moose',
		'music',
		'news',
		'patience',
		'progress',
		'pollution',
		'research',
		'rice',
		'salmon',
		'sand',
		'series',
		'sheep',
		'sms',
		'spam',
		'species',
		'staff',
		'swine',
		'toothpaste',
		'traffic',
		'understanding',
		'water',
		'weather',
		'work',
	),

	'irregular' => array(
		'child' => 'children',
		'clothes' => 'clothing',
		'man' => 'men',
		'movie' => 'movies',
		'person' => 'people',
		'woman' => 'women',
		'mouse' => 'mice',
		'goose' => 'geese',
		'ox' => 'oxen',
		'leaf' => 'leaves',
		'course' => 'courses',
		'size' => 'sizes',
		'was' => 'were',
		'is' => 'are',
		'verse' => 'verses',
		'hero' => 'heroes',
		'purchase' => 'purchases',
		'expense' => 'expenses',
	),
);
